name: snaplist
region: nyc

# Database - Digital Ocean Managed PostgreSQL
databases:
  - name: snaplist-db
    engine: PG
    version: "16"
    production: true
    cluster_name: snaplist-db-cluster

# Main web service
services:
  - name: web
    # Source code
    github:
      repo: your-github-username/SnapList
      branch: main
      deploy_on_push: true
    
    # Build configuration
    build_command: npm install && npm run build
    run_command: npm start
    
    # Environment
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # HTTP configuration
    http_port: 5000
    
    # Health check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Environment variables
    envs:
      # Database (automatically injected by Digital Ocean)
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
        value: ${snaplist-db.DATABASE_URL}
      
      # Node environment
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: production
      
      # Server configuration
      - key: PORT
        scope: RUN_TIME
        value: "5000"
      
      # JWT & Session secrets (set these in Digital Ocean dashboard)
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      
      - key: SESSION_SECRET
        scope: RUN_TIME
        type: SECRET
      
      # Stripe configuration (set in Digital Ocean dashboard)
      - key: STRIPE_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      
      - key: STRIPE_PUBLISHABLE_KEY
        scope: RUN_AND_BUILD_TIME
        value: "pk_test_your_key"
      
      - key: VITE_STRIPE_PUBLIC_KEY
        scope: BUILD_TIME
        value: "pk_test_your_key"
      
      - key: STRIPE_STANDARD_PRICE_ID
        scope: RUN_TIME
        value: "price_1SD9ShDtmSuWvYXlHQLZbM77"
      
      - key: STRIPE_PRO_PRICE_ID
        scope: RUN_TIME
        value: "price_1SD9T7DtmSuWvYXlQhTn40Oj"
      
      - key: STRIPE_WEBHOOK_SECRET
        scope: RUN_TIME
        type: SECRET
      
      # OAuth configuration (optional - set in Digital Ocean dashboard if needed)
      - key: GOOGLE_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      
      - key: GOOGLE_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      
      - key: FACEBOOK_APP_ID
        scope: RUN_TIME
        type: SECRET
      
      - key: FACEBOOK_APP_SECRET
        scope: RUN_TIME
        type: SECRET
      
      # Google Maps API (if used)
      - key: VITE_GOOGLE_MAPS_API_KEY
        scope: BUILD_TIME
        type: SECRET

# Static site option (if you want to separate frontend)
# static_sites:
#   - name: snaplist-frontend
#     github:
#       repo: your-github-username/SnapList
#       branch: main
#       deploy_on_push: true
#     build_command: npm run build:client
#     output_dir: dist/public
#     routes:
#       - path: /

