name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests (if available)
        run: npm test --if-present
        continue-on-error: true
      
      - name: Build application
        run: npm run build
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Deploy to Digital Ocean
        run: |
          # Get the app ID from secrets or environment
          APP_ID="${{ secrets.DIGITALOCEAN_APP_ID }}"
          
          if [ -z "$APP_ID" ]; then
            echo "DIGITALOCEAN_APP_ID secret is not set!"
            echo "Please add your Digital Ocean App ID to GitHub secrets"
            echo "Or deploy manually using: doctl apps create --spec .do/app.yaml"
            exit 1
          fi
          
          # Trigger deployment
          doctl apps create-deployment $APP_ID --wait
      
      - name: Verify deployment
        run: |
          APP_ID="${{ secrets.DIGITALOCEAN_APP_ID }}"
          echo "Deployment completed!"
          echo "Check your app status at: https://cloud.digitalocean.com/apps/$APP_ID"
      
      - name: Notify on failure
        if: failure()
        run: |
          echo "Deployment failed! Check the logs above for details."
          echo "Manual deployment may be required."

